InvestProject:
  server: mssql
  host: 192.168.1.1
  db: InvestProjectTable
  user: xxx
  pass: xxx

InvestApprove:
  server: mssql
  host: 192.168.1.1
  db: InvestApproveTable
  user: xxx
  pass: xxx