InvestProject:
  server: mssql
  host: 192.168.2.202
  db: InvestProjData
  user: qzppbdata
  pass: qzdata159@Qz

InvestApprove:
  server: mssql
  host: 192.168.2.202
  db: InvestProjData
  user: qzppbdata
  pass: qzdata159@Qz